version: "3"

services:
  nginx-jobhunt:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    hostname: nginx-jobhunt
    networks:
      - webproxy
      - jobhunt-app
    expose:
      - "80"
      - "443"
    environment:
      VIRTUAL_HOST: jobhunt.kathyebel.dev
      LETSENCRYPT_HOST: jobhunt.kathyebel.dev
      LETSENCRYPT_EMAIL: hello@katherineebel.com
      NODE_ENV: production
  jobhunt-client:
    hostname: jobhunt-client
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - API_URL=jobhunt-api/api/v1
    restart: always
    networks:
      - jobhunt-app
    env_file:
      - ./apps/web/.env.development
  jobhunt-api:
    hostname: jobhunt-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    networks:
      - jobhunt-app
    env_file:
      - ./apps/api/.env.production

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  webproxy:
    external: true
  jobhunt-app:
