version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - URI=http://localhost:3001/api/v1
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network
    env_file:
      - ./apps/web/.env.development
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    networks:
      - app_network
    env_file:
      - ./apps/api/.env.production

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
